spring.application.name=cursos


# Basic configuration
scalar.url=/v3/api-docs
scalar.path=/docs
scalar.enabled=true
# UI customization
scalar.theme=bluePlanet
scalar.layout=modern
springdoc.show-actuator=false
springdoc.packages-to-scan=edu.utfpr.cursos.controller